version: "3.9"
services:
    web:
        build: ./packages/pl.client
        container_name: riogz.client
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        volumes:
          - ./packages/pl.client/dist:/app