version: "3.9"
services:
    postgres:
        image: postgres:15.4-alpine
        ports:
            - ${DATABASE_PORT}:5432
        volumes:
            - ./.data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}

    maildev:
        build:
            context: .
            dockerfile: maildev.Dockerfile
        ports:
            - ${MAIL_CLIENT_PORT}:1080
            - ${MAIL_PORT}:1025

#    redis:
#       image: redis:7-alpine
#       ports:
#         - 6379:6379

    api:
        image: riogod/riogz.dev
#        image: api-2:tag
        container_name: api
        restart: always
        expose:
            - 5500
        env_file:
            - ./packages/api/1.env